name = "busuanzi"
main = "src/index.js"
compatibility_date = "2025-04-01"
workers_dev = true

routes = [
  { pattern = "bsz.oopss.top", custom_domain = true },
  { pattern = "ac.oopss.top", custom_domain = true }
]

[[kv_namespaces]]
binding = "BUSUANZI"
id = "1ff40dc8c4d545f2b593f686911ce369"
